#!/bin/bash
# Legt in einem laufenden Docker-Container "container_name: mariadb" Schema, User und Privileges an.

BEM_DB_SCHEMA=bem_dev
BEM_DB_SCHEMA_LP=bem_dev_lp
BEM_DB_SCHEMA_METABASE=bem_dev_metabase
BEM_DB_USER=bem_dev
BEM_DB_USER_LP=bem_dev_lp

PORT=3308
THIS_SCRIPT=mariaDB-Schema.sh


# Weiterleitung an laufenden Docker-Container "mariadb"
docker exec -i mariadb mysql -u root -proot <<EOF
DROP DATABASE IF EXISTS $BEM_DB_SCHEMA;
DROP DATABASE IF EXISTS $BEM_DB_SCHEMA_LP;
DROP DATABASE IF EXISTS $BEM_DB_SCHEMA_METABASE;

# = = leere Database und User in DB anlegen
CREATE DATABASE $BEM_DB_SCHEMA          CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE DATABASE $BEM_DB_SCHEMA_LP       CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE DATABASE $BEM_DB_SCHEMA_METABASE CHARACTER SET utf8 COLLATE utf8_general_ci;

DROP USER IF EXISTS $BEM_DB_USER;
DROP USER IF EXISTS $BEM_DB_USER_LP;
CREATE USER '$BEM_DB_USER'    IDENTIFIED BY '$BEM_DB_USER';
CREATE USER '$BEM_DB_USER_LP' IDENTIFIED BY '$BEM_DB_USER_LP';

GRANT ALL PRIVILEGES ON $BEM_DB_SCHEMA.*          TO '$BEM_DB_USER';
GRANT ALL PRIVILEGES ON $BEM_DB_SCHEMA_LP.*       TO '$BEM_DB_USER_LP';
GRANT ALL PRIVILEGES ON $BEM_DB_SCHEMA_METABASE.* TO '$BEM_DB_USER';

# über Kreuz lesen
GRANT SELECT, SHOW VIEW, CREATE VIEW ON $BEM_DB_SCHEMA.*    TO '$BEM_DB_USER_LP';
GRANT SELECT, SHOW VIEW, CREATE VIEW ON $BEM_DB_SCHEMA_LP.* TO '$BEM_DB_USER';

FLUSH PRIVILEGES;
commit;

EOF

echo "$THIS_SCRIPT: done"

