name: loginAWS

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #  branches: [ "main" ]
  # pull_request:
  #  branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  setup-image:
    runs-on: ubuntu-latest
              
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to AWS ECR
        uses: aws-actions/aws-ecr-login@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Pull and Run Docker image
        run: |
          # docker pull your-aws-ecr-repository/your-image-name:latest
          docker pull ${{ secrets.AWS_ECR_REPOSITORY }}/bem_local_dev:latest
          
          docker run -d --name bem-container \
          -p 8080:8080 \
          --env DATABASE_HOST=mariadb \
          --env DATABASE_PORT=3306 \
          --env DATABASE_USER=root \
          --env DATABASE_PASSWORD=root \
          --env DATABASE_NAME=mydatabase \
          ${{ secrets.AWS_ECR_REPOSITORY }}/bem_local_dev:latest
          
      - name: Wait for WebApp to be ready
        run: sleep 10

      - name: Test WebApp access
        run: curl http://localhost:8080/health
