name: setupBEM2

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #  branches: [ "main" ]
  # pull_request:
  #  branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  setup-mariadb:
    runs-on: ubuntu-latest
    
    # Hier wird der MariaDB-Service definiert
    services:
      mariadb:
        image: mariadb:10.6
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: mydatabase
        ports:
          - 3306:3306 # Optional, um den Port nach außen zu mappen
          
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Jetzt kann direkt auf den Service "mariadb" zugegriffen werden
      - name: Import MariaDB dump
        run: |
          # Der Hostname ist der Service-Name
          mariadb -u root -proot -h mariadb mydatabase < dump/database.sql

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Pull Docker image
        run: |
          IMAGE_URI=780470227703.dkr.ecr.eu-central-1.amazonaws.com/bem_local_dev:latest
          echo "Pulling $IMAGE_URI"
          docker pull $IMAGE_URI
      

