name: setupBEM2

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #  branches: [ "main" ]
  # pull_request:
  #  branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  setup-mariadb:
    runs-on: ubuntu-latest
    
    # Hier wird der MariaDB-Service definiert
    services:
      mariadb:
        image: mariadb:10.6
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: mydatabase
        ports:
          - 3306:3306 # Optional, um den Port nach außen zu mappen
          
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Jetzt kann direkt auf den Service "mariadb" zugegriffen werden
      - name: Import MariaDB dump
        run: |
          # Der Hostname ist der Service-Name
          mariadb -u root -proot -h mariadb mydatabase < dump/database.sql


